input_data:
  airbnb:
    file: "data/raw/airnb.csv"

  desert:
    file: "data/raw/airnb_desert.csv"

  luxe:
    file: "data/raw/airnb_luxe.csv"

output_data:
  cleaned:
    file: "data/clean/airbnb_cleaned copy.csv"
